import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

// Auth-scoped (verify_jwt: true) — called by the iOS app with the caller's
// real Supabase session (Authorization: Bearer <accessToken>). Returns the
// caller's own ongoing partner invite code (profiles.is_partner = true only),
// generating one on first fetch. One code per partner, unlimited
// redemptions, never regenerated by the user — Will revokes a specific code
// manually in Supabase if needed.
//
// Companion: redeem-invite-code (verify_jwt: false) — the redemption/grant
// side of this feature.

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;

const CORS_HEADERS: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
  });
}

const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

// No 0/O/1/I — avoids ambiguity when a partner reads the code aloud or
// retypes it from a screenshot.
const SUFFIX_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

function randomSuffix(length = 4): string {
  let out = "";
  for (let i = 0; i < length; i++) {
    out += SUFFIX_ALPHABET[Math.floor(Math.random() * SUFFIX_ALPHABET.length)];
  }
  return out;
}

function baseFromSlug(slug: string): string {
  const cleaned = slug.toUpperCase().replace(/[^A-Z0-9]/g, "");
  return cleaned.slice(0, 12) || "SQRZ";
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: CORS_HEADERS });
  if (req.method !== "POST") return json({ ok: false, code: "method_not_allowed" }, 405);

  const authHeader = req.headers.get("Authorization");
  const userClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: authHeader ?? "" } },
  });
  const { data: userData, error: userError } = await userClient.auth.getUser();
  if (userError || !userData.user) {
    return json({ ok: false, code: "unauthorized" }, 401);
  }

  // profiles.id != auth.users.id — always resolve via user_id first.
  const { data: profile, error: profileError } = await admin
    .from("profiles")
    .select("id, slug, is_partner")
    .eq("user_id", userData.user.id)
    .single();

  if (profileError || !profile) {
    return json({ ok: false, code: "profile_not_found" }, 404);
  }
  if (!profile.is_partner) {
    return json({ ok: false, code: "not_a_partner" }, 403);
  }

  // Already has a code?
  const { data: existing, error: existingError } = await admin
    .from("invite_codes")
    .select("code, max_redemptions, redemption_count, created_at")
    .eq("referrer_id", profile.id)
    .maybeSingle();

  if (existingError) {
    console.error("invite_codes lookup error:", existingError);
    return json({ ok: false, code: "lookup_failed" }, 500);
  }
  if (existing) {
    return json({ ok: true, invite_code: existing });
  }

  // Create one — retry on the rare suffix collision (unique PK on `code`).
  const base = baseFromSlug(profile.slug ?? "");
  let lastError: unknown = null;
  for (let attempt = 0; attempt < 5; attempt++) {
    const candidate = `${base}-${randomSuffix()}`;
    const { data: inserted, error: insertError } = await admin
      .from("invite_codes")
      .insert({
        code: candidate,
        referrer_id: profile.id,
        created_by: profile.id,
        max_redemptions: null, // unlimited — the partner's ongoing code, not single-use
      })
      .select("code, max_redemptions, redemption_count, created_at")
      .single();

    if (!insertError) {
      return json({ ok: true, invite_code: inserted });
    }
    if ((insertError as { code?: string }).code !== "23505") {
      console.error("invite_codes insert error:", insertError);
      return json({ ok: false, code: "create_failed" }, 500);
    }
    lastError = insertError;
  }

  console.error("invite_codes insert: exhausted retries", lastError);
  return json({ ok: false, code: "create_failed" }, 500);
});
